"""Build a signalized grid scenario for SUMO.

Writes plain XML (nodes/edges), runs netconvert, then writes background traffic
(routes.rou.xml) and simulation.sumocfg into scenarios/grid<nx>x<ny>/.

Run from the repo root with the backend venv:
    backend\\.venv\\Scripts\\python.exe scenarios\\build_grid.py
    backend\\.venv\\Scripts\\python.exe scenarios\\build_grid.py --nx 4 --ny 4

Naming: signalized junctions are <column letter><row digit> (A0 is south-west).
Map-edge nodes are n<col>/s<col>/w<row>/e<row>. Edges are <from>_<to>.
"""

from __future__ import annotations

import argparse
import json
import string
import subprocess
import sys
from dataclasses import asdict, dataclass
from pathlib import Path

import sumolib
from dotenv import load_dotenv

SCENARIOS_DIR = Path(__file__).resolve().parent
REPO_ROOT = SCENARIOS_DIR.parent

# Background vehicle types. The vType id doubles as the 3D asset key.
# (id, vClass, length m, width m, share of background traffic)
# Trucks and buses are defined but get 0% share: with permissive (yielding) turns,
# long vehicles waiting inside these junctions overlap crossing traffic, and SUMO
# reported 1-11 junction collisions per hour at 1.5x demand. Cars-only: 0.
VTYPES: tuple[tuple[str, str, float, float, float], ...] = (
    ("car_sedan", "passenger", 4.5, 1.8, 0.70),
    ("car_hatchback", "passenger", 3.9, 1.7, 0.30),
    ("truck", "truck", 7.5, 2.4, 0.0),
    ("bus", "bus", 12.0, 2.5, 0.0),
)

# Manually driven ambulance. speedFactor 1.6 lets it reach the 22 m/s cap on 50 km/h roads;
# accel/decel match the manual-control constants; no driver randomness (sigma, speedDev).
AMBULANCE_VTYPE = (
    '<vType id="ambulance" vClass="emergency" length="6.0" width="2.2" maxSpeed="22.0" '
    'speedFactor="1.6" speedDev="0" accel="3.5" decel="6.0" emergencyDecel="9.0" sigma="0" '
    'guiShape="emergency"/>'
)
HOSPITAL_STOP_BEFORE_END = 15.0  # m before the end of the hospital edge


@dataclass(frozen=True)
class GridSpec:
    nx: int = 2
    ny: int = 2
    spacing: float = 250.0  # m between signalized junctions
    arm: float = 200.0  # m from the outer junctions to the map edge
    lanes: int = 2  # per direction
    speed: float = 13.89  # m/s (50 km/h)
    lefthand: bool = True  # India
    green: int = 31  # s
    yellow: int = 4  # s
    allred: int = 2  # s
    entry_rate: float = 400.0  # veh/h entering at each map-edge road, at --scale 1.0
    end: int = 3600  # s
    seed: int = 42


@dataclass(frozen=True)
class Node:
    id: str
    x: float
    y: float
    signalized: bool


def build_nodes(spec: GridSpec) -> list[Node]:
    cols = string.ascii_uppercase[: spec.nx]
    top = 2 * spec.arm + (spec.ny - 1) * spec.spacing
    right = 2 * spec.arm + (spec.nx - 1) * spec.spacing
    nodes: list[Node] = []
    for c, col in enumerate(cols):
        x = spec.arm + c * spec.spacing
        nodes += [Node(f"{col}{r}", x, spec.arm + r * spec.spacing, True) for r in range(spec.ny)]
        nodes += [Node(f"s{col}", x, 0.0, False), Node(f"n{col}", x, top, False)]
    for r in range(spec.ny):
        y = spec.arm + r * spec.spacing
        nodes += [Node(f"w{r}", 0.0, y, False), Node(f"e{r}", right, y, False)]
    return nodes


def build_links(spec: GridSpec) -> list[tuple[str, str]]:
    """Undirected neighbour pairs; the first node of a map-edge pair is the map-edge node."""
    cols = string.ascii_uppercase[: spec.nx]
    links: list[tuple[str, str]] = []
    for col in cols:
        links.append((f"s{col}", f"{col}0"))
        links += [(f"{col}{r}", f"{col}{r + 1}") for r in range(spec.ny - 1)]
        links.append((f"n{col}", f"{col}{spec.ny - 1}"))
    for r in range(spec.ny):
        links.append((f"w{r}", f"A{r}"))
        links += [(f"{cols[c]}{r}", f"{cols[c + 1]}{r}") for c in range(spec.nx - 1)]
        links.append((f"e{r}", f"{cols[-1]}{r}"))
    return links


def map_edge_roads(nodes: list[Node], links: list[tuple[str, str]]) -> list[tuple[str, str, str]]:
    """(map-edge node, entry edge id, exit edge id) for every road that leaves the map."""
    fringe = {n.id for n in nodes if not n.signalized}
    return [(a, f"{a}_{b}", f"{b}_{a}") for a, b in links if a in fringe]


def write_plain_xml(
    spec: GridSpec, out: Path, nodes: list[Node], links: list[tuple[str, str]]
) -> None:
    header = f"<!-- generated by scenarios/build_grid.py: {asdict(spec)} -->\n"
    node_lines = [
        f'    <node id="{n.id}" x="{n.x:.2f}" y="{n.y:.2f}" '
        f'type="{"traffic_light" if n.signalized else "priority"}"/>'
        for n in nodes
    ]
    edge_lines = [
        f'    <edge id="{a}_{b}" from="{a}" to="{b}" numLanes="{spec.lanes}" speed="{spec.speed}"/>'
        for u, v in links
        for a, b in ((u, v), (v, u))
    ]
    (out / "grid.nod.xml").write_text(header + "<nodes>\n" + "\n".join(node_lines) + "\n</nodes>\n")
    (out / "grid.edg.xml").write_text(header + "<edges>\n" + "\n".join(edge_lines) + "\n</edges>\n")


def run_netconvert(spec: GridSpec, out: Path) -> None:
    # fmt: off
    cmd = [
        sumolib.checkBinary("netconvert"),
        "--node-files", "grid.nod.xml",
        "--edge-files", "grid.edg.xml",
        "--output-file", "network.net.xml",
        "--offset.disable-normalization",  # keep the coordinates above (A0 at arm, arm)
        "--tls.default-type", "static",
        "--tls.layout", "opposites",
        "--tls.green.time", str(spec.green),
        "--tls.yellow.time", str(spec.yellow),
        "--tls.allred.time", str(spec.allred),
        "--no-turnarounds.tls",  # no U-turns at signals; map-edge nodes keep theirs
        "--junctions.corner-detail", "5",
    ]
    # fmt: on
    if spec.lefthand:
        cmd.append("--lefthand")
    subprocess.run(cmd, cwd=out, check=True)


def write_routes(spec: GridSpec, out: Path, roads: list[tuple[str, str, str]]) -> None:
    """Poisson flows from every map-edge road to every other one (seed-dependent arrivals)."""
    rate = spec.entry_rate / 3600.0 / (len(roads) - 1)  # veh/s per origin-destination pair
    lines = ["<routes>"]
    for vid, vclass, length, width, _ in VTYPES:
        lines.append(f'    <vType id="{vid}" vClass="{vclass}" length="{length}" width="{width}"/>')
    ids = " ".join(v[0] for v in VTYPES)
    shares = " ".join(str(v[4]) for v in VTYPES)
    lines.append(
        f'    <vTypeDistribution id="background" vTypes="{ids}" probabilities="{shares}"/>'
    )
    lines.append(f"    {AMBULANCE_VTYPE}")
    for src, entry, _ in roads:
        for dst, _, exit_edge in roads:
            if src == dst:
                continue
            lines.append(
                f'    <flow id="f_{src}_{dst}" type="background" begin="0" end="{spec.end}" '
                f'from="{entry}" to="{exit_edge}" period="exp({rate:.6f})" '
                f'departLane="best" departSpeed="max"/>'
            )
    lines.append("</routes>")
    header = f"<!-- generated by scenarios/build_grid.py: {asdict(spec)} -->\n"
    (out / "routes.rou.xml").write_text(header + "\n".join(lines) + "\n")


def write_sumocfg(spec: GridSpec, out: Path) -> None:
    (out / "simulation.sumocfg").write_text(f"""\
<!-- generated by scenarios/build_grid.py -->
<configuration>
    <input>
        <net-file value="network.net.xml"/>
        <route-files value="routes.rou.xml"/>
    </input>
    <time>
        <begin value="0"/>
        <end value="{spec.end}"/>
        <step-length value="0.1"/>
    </time>
    <processing>
        <lanechange.duration value="1.5"/>
        <time-to-teleport value="300"/>
        <collision.action value="warn"/>
        <collision.check-junctions value="true"/>
    </processing>
    <random_number>
        <seed value="{spec.seed}"/>
    </random_number>
    <report>
        <no-step-log value="true"/>
        <duration-log.disable value="true"/>
    </report>
</configuration>
""")


def write_scenario(spec: GridSpec, out: Path) -> None:
    """Depot (west edge, bottom row) and hospital (east edge, top row): a diagonal trip."""
    last_col, top = string.ascii_uppercase[spec.nx - 1], spec.ny - 1
    scenario = {
        "depot": {"edge": "w0_A0", "pos": 0.0},
        "hospital": {"edge": f"{last_col}{top}_e{top}", "stopBeforeEnd": HOSPITAL_STOP_BEFORE_END},
    }
    (out / "scenario.json").write_text(json.dumps(scenario, indent=2) + "\n")


def describe_signals(out: Path) -> None:
    net = sumolib.net.readNet(str(out / "network.net.xml"), withPrograms=True)
    for tls in sorted(net.getTrafficLights(), key=lambda t: t.getID()):
        for program_id, program in tls.getPrograms().items():
            phases = program.getPhases()
            cycle = sum(p.duration for p in phases)
            print(f"  {tls.getID()} program {program_id}: cycle {cycle:g} s")
            for i, p in enumerate(phases):
                print(f"    phase {i}: {p.state}  {p.duration:g} s")


def main(argv: list[str] | None = None) -> int:
    defaults = GridSpec()
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--nx", type=int, default=defaults.nx)
    parser.add_argument("--ny", type=int, default=defaults.ny)
    parser.add_argument("--entry-rate", type=float, default=defaults.entry_rate)
    parser.add_argument("--righthand", action="store_true", help="right-hand traffic")
    parser.add_argument("--out", type=Path, default=None)
    args = parser.parse_args(argv)
    if not (1 <= args.nx <= 26 and 1 <= args.ny <= 10):
        parser.error("nx must be 1-26 and ny 1-10")

    load_dotenv(REPO_ROOT / ".env")
    spec = GridSpec(nx=args.nx, ny=args.ny, entry_rate=args.entry_rate, lefthand=not args.righthand)
    out = args.out or SCENARIOS_DIR / f"grid{spec.nx}x{spec.ny}"
    out.mkdir(parents=True, exist_ok=True)

    nodes, links = build_nodes(spec), build_links(spec)
    write_plain_xml(spec, out, nodes, links)
    run_netconvert(spec, out)
    write_routes(spec, out, map_edge_roads(nodes, links))
    write_sumocfg(spec, out)
    write_scenario(spec, out)
    print(f"Built {out}")
    describe_signals(out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
