/**
 * Where the props of an accident go, in the wreck's local frame: +Z is the direction of
 * travel (glTF forward), so upstream traffic arrives from -Z. Pure, for tests.
 *
 * The wreck stands in its lane; a barrier just behind it and a cone taper further back
 * close that lane, guiding traffic into the open one.
 */
import type { AssetKey } from "../assets/manifest";

export interface IncidentProp {
  asset: AssetKey;
  position: [number, number, number]; // m, local frame (x across the road, z along it)
  rotationY: number;
}

export const LANE_WIDTH = 3.2; // m, as generated by build_grid.py
const CONE_TAPER: [number, number][] = [
  // [fraction from the lane's outer edge (0) to its open side (1), metres upstream]
  [0.15, 20],
  [0.4, 15],
  [0.65, 10.5],
  [0.88, 6.5],
];
const WRECK_ASKEW = 0.42; // rad: a crashed car rarely stands straight

/**
 * Which way (+1 or -1 along local x) the open lane lies. Facing +Z, local +x is the
 * driver's left. Lane 0 is the curb lane: the open lane is to its right in left-hand
 * traffic and to its left in right-hand traffic.
 */
export function openSide(lane: number, lefthand: boolean): 1 | -1 {
  const inner = lefthand ? -1 : 1;
  return (lane === 0 ? inner : -inner) as 1 | -1;
}

export function incidentProps(lane: number, lefthand: boolean): IncidentProp[] {
  const side = openSide(lane, lefthand);
  const half = LANE_WIDTH / 2;
  const props: IncidentProp[] = [
    { asset: "wrecked_car", position: [-side * 0.2, 0, 0], rotationY: side * WRECK_ASKEW },
    { asset: "barricade", position: [0, 0, -4.5], rotationY: 0 },
    { asset: "road_block", position: [-side * 0.6, 0, -24], rotationY: 0 },
  ];
  for (const [f, back] of CONE_TAPER) {
    props.push({ asset: "cone", position: [side * (-half + f * LANE_WIDTH), 0, -back], rotationY: 0 });
  }
  return props;
}
