// GENERATED by backend/scripts/gen_contract.py from backend/api/protocol.py.
// Do not edit. Regenerate from backend/:
//   .venv\Scripts\python.exe -m scripts.gen_contract
// Each fixture `satisfies` the hand-written type in state.ts: drift fails to compile.
import type {
  AckMsg,
  Command,
  ErrorMsg,
  HealthMsg,
  NetworkMsg,
  SessionMsg,
  StateMsg,
} from "./state";

export const stateDriving = {
  "v": 1,
  "type": "state",
  "seq": 1234,
  "t": 123.4,
  "mode": "BASIC",
  "vehicles": [
    {
      "id": "ambulance_01",
      "type": "ambulance",
      "x": 421.4,
      "y": 193.2,
      "angle": 90.0,
      "speed": 16.8,
      "edge": "A0_B0",
      "lane": 1
    },
    {
      "id": "f_w0_e0.3",
      "type": "car_sedan",
      "x": 300.1,
      "y": 204.8,
      "angle": 90.0,
      "speed": 12.5,
      "edge": ":A0_13_0",
      "lane": 0
    }
  ],
  "signals": [
    {
      "id": "B0",
      "state": "rrrrrrrrrrrrGGGG",
      "phase": 0,
      "preempted": true,
      "control": "preempted"
    },
    {
      "id": "A0",
      "state": "GGGgrrrrGGGgrrrr",
      "phase": 0,
      "preempted": false,
      "control": "program"
    }
  ],
  "ambulance": {
    "id": "ambulance_01",
    "status": "driving",
    "throttle": 1.0,
    "brake": 0.0,
    "nextSignal": {
      "junction": "B0",
      "linkIndex": 13,
      "distance": 84.2,
      "state": "G"
    },
    "plannedTurn": {
      "junction": "B0",
      "turn": "left",
      "edge": "B0_B1"
    },
    "queuedTurn": "right",
    "missionTime": 41.5
  },
  "route": null,
  "metrics": {
    "eta": null,
    "signalsPreempted": 2,
    "queueCleared": null,
    "timeSaved": null
  },
  "safety": {
    "violations": 0,
    "collisions": 0,
    "events": [
      {
        "t": 18.4,
        "junction": "B0",
        "vehicle": "ambulance_01",
        "action": "preempt",
        "accepted": true,
        "reason": "ETA 14.5 s: clearing B0 for A0_B0"
      },
      {
        "t": 19.0,
        "junction": "B1",
        "vehicle": null,
        "action": "preempt",
        "accepted": false,
        "reason": "unknown junction B1"
      }
    ]
  },
  "incidents": []
} satisfies StateMsg;

export const stateIdle = {
  "v": 1,
  "type": "state",
  "seq": 1,
  "t": 0.1,
  "mode": "OFF",
  "vehicles": [],
  "signals": [
    {
      "id": "A0",
      "state": "GGGgrrrrGGGgrrrr",
      "phase": 0,
      "preempted": false,
      "control": "program"
    }
  ],
  "ambulance": {
    "id": "ambulance_01",
    "status": "none",
    "throttle": 0.0,
    "brake": 0.0,
    "nextSignal": null,
    "plannedTurn": null,
    "queuedTurn": null,
    "missionTime": null
  },
  "route": null,
  "metrics": {
    "eta": null,
    "signalsPreempted": 0,
    "queueCleared": null,
    "timeSaved": null
  },
  "safety": {
    "violations": 0,
    "collisions": 0,
    "events": []
  },
  "incidents": []
} satisfies StateMsg;

export const ackRejected = {
  "v": 1,
  "type": "ack",
  "id": 3,
  "ok": false,
  "reason": "no lane further left"
} satisfies AckMsg;

export const ackAccepted = {
  "v": 1,
  "type": "ack",
  "id": 4,
  "ok": true,
  "reason": ""
} satisfies AckMsg;

export const error = {
  "v": 1,
  "type": "error",
  "reason": "message is not valid JSON"
} satisfies ErrorMsg;

export const sessionDriver = {
  "v": 1,
  "type": "session",
  "clientId": "tab-0123456789",
  "role": "driver"
} satisfies SessionMsg;

export const network = {
  "v": 1,
  "lefthand": true,
  "bounds": [
    0.0,
    0.0,
    650.0,
    650.0
  ],
  "lanes": [
    {
      "id": "A0_A1_0",
      "edge": "A0_A1",
      "index": 0,
      "width": 3.2,
      "shape": [
        [
          195.2,
          210.4
        ],
        [
          195.2,
          439.6
        ]
      ]
    },
    {
      "id": "A0_A1_1",
      "edge": "A0_A1",
      "index": 1,
      "width": 3.2,
      "shape": [
        [
          198.4,
          210.4
        ],
        [
          198.4,
          439.6
        ]
      ]
    }
  ],
  "junctions": [
    {
      "id": "A0",
      "type": "traffic_light",
      "shape": [
        [
          193.6,
          189.6
        ],
        [
          206.4,
          189.6
        ],
        [
          206.84,
          191.82
        ],
        [
          207.4,
          192.6
        ],
        [
          208.18,
          193.16
        ],
        [
          209.18,
          193.49
        ],
        [
          210.4,
          193.6
        ],
        [
          210.4,
          206.4
        ],
        [
          208.18,
          206.84
        ],
        [
          207.4,
          207.4
        ],
        [
          206.84,
          208.18
        ],
        [
          206.51,
          209.18
        ],
        [
          206.4,
          210.4
        ],
        [
          193.6,
          210.4
        ],
        [
          193.16,
          208.18
        ],
        [
          192.6,
          207.4
        ],
        [
          191.82,
          206.84
        ],
        [
          190.82,
          206.51
        ],
        [
          189.6,
          206.4
        ],
        [
          189.6,
          193.6
        ],
        [
          191.82,
          193.16
        ],
        [
          192.6,
          192.6
        ],
        [
          193.16,
          191.82
        ],
        [
          193.49,
          190.82
        ]
      ]
    }
  ],
  "signals": [
    {
      "id": "A0",
      "links": [
        {
          "index": 0,
          "fromLane": "sA_A0_0",
          "toLane": "A0_w0_0",
          "dir": "l",
          "approach": "sA_A0"
        },
        {
          "index": 1,
          "fromLane": "sA_A0_0",
          "toLane": "A0_A1_0",
          "dir": "s",
          "approach": "sA_A0"
        }
      ]
    }
  ],
  "depot": {
    "edge": "w0_A0",
    "pos": 0.0,
    "x": 0.0,
    "y": 204.8
  },
  "hospital": {
    "edge": "B1_e1",
    "pos": 174.6,
    "x": 635.0,
    "y": 454.8
  }
} satisfies NetworkMsg;

export const health = {
  "status": "running",
  "error": null,
  "seq": 10,
  "t": 1.0,
  "vehicles": 5,
  "tickMsP50": 2.1,
  "tickMsP95": 4.0,
  "tickMsMax": 6.3,
  "sumoStepMsP50": 1.9
} satisfies HealthMsg;

export const healthStarting = {
  "status": "starting",
  "error": null,
  "seq": null,
  "t": null,
  "vehicles": 0,
  "tickMsP50": null,
  "tickMsP95": null,
  "tickMsMax": null,
  "sumoStepMsP50": null
} satisfies HealthMsg;

export const commands = [
  {
    "v": 1,
    "id": 1,
    "cmd": "spawn_ambulance"
  },
  {
    "v": 1,
    "cmd": "drive",
    "vehicle": "ambulance_01",
    "control": {
      "throttle": 1.0,
      "brake": 0.0
    }
  },
  {
    "v": 1,
    "id": 2,
    "cmd": "turn",
    "vehicle": "ambulance_01",
    "direction": "left"
  },
  {
    "v": 1,
    "id": 3,
    "cmd": "lane",
    "vehicle": "ambulance_01",
    "direction": "right"
  },
  {
    "v": 1,
    "id": 4,
    "cmd": "set_mode",
    "mode": "BASIC"
  },
  {
    "v": 1,
    "id": 5,
    "cmd": "reset"
  },
  {
    "v": 1,
    "cmd": "hello",
    "clientId": "tab-0123456789"
  },
  {
    "v": 1,
    "id": 6,
    "cmd": "release_control"
  }
] satisfies Command[];

export const BACKEND_COMMANDS = ["spawn_ambulance", "drive", "turn", "lane", "set_mode", "reset", "hello", "release_control"] as const;
export const BACKEND_SERVER_TYPES = ["state", "ack", "error", "session"] as const;
export const BACKEND_ENUMS = {
  "role": [
    "driver",
    "observer",
    "free"
  ],
  "mode": [
    "OFF",
    "BASIC",
    "COORD"
  ],
  "signalControl": [
    "program",
    "clearing",
    "preempted",
    "recovering"
  ],
  "missionStatus": [
    "none",
    "pending",
    "driving",
    "arrived"
  ],
  "turn": [
    "left",
    "straight",
    "right",
    "uturn"
  ],
  "healthStatus": [
    "starting",
    "running",
    "error"
  ]
} as const;
